name: Scheduled Bankin Scraper

on:
  schedule:
    # Run daily at 9 AM UTC (adjust timezone as needed)
    - cron: "0 9 * * *"
  workflow_dispatch: # Allow manual trigger from GitHub Actions tab

jobs:
  trigger-railway-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Railway Deployment
        run: |
          echo "🚂 Triggering Railway deployment..."
          curl -X POST "${{ secrets.RAILWAY_WEBHOOK_URL }}" \
            -H "Content-Type: application/json" \
            -d '{"ref": "main"}'

      - name: Notify completion
        run: |
          echo "✅ Railway deployment triggered successfully!"
          echo "Check your Railway dashboard for deployment status."
